import { Component, effect, inject, signal } from '@angular/core';
import { NavigationCancel, NavigationEnd, NavigationError, NavigationSkipped, NavigationStart, Router, RouterLink, RouterLinkActive, RouterOutlet } from '@angular/router';
@Component({selector:'app-root',imports:[RouterOutlet,RouterLink,RouterLinkActive],template:`
<header class="topbar"><a class="skip" href="#content">Pular para o conteúdo</a><div class="container nav"><a routerLink="/" class="logo" aria-label="Juvino Tech, início"><span>J</span> Juvino Tech</a><button class="menu-btn" (click)="menu.set(!menu())" [attr.aria-expanded]="menu()" aria-label="Abrir menu">☰</button><nav [class.open]="menu()"><a routerLink="/artigos" routerLinkActive="active" (click)="menu.set(false)">Artigos</a><a routerLink="/sobre" routerLinkActive="active" (click)="menu.set(false)">Sobre</a><a href="https://github.com/joao-juvino" target="_blank" rel="noopener noreferrer">GitHub ↗</a><button class="theme" (click)="toggleTheme()" [attr.aria-label]="dark()?'Ativar tema claro':'Ativar tema escuro'">{{dark()?'☀':'☾'}}</button></nav></div></header>
@if (navigating()) { <div class="route-progress" role="progressbar" aria-label="Carregando página"></div> }
<main id="content"><router-outlet/></main>
<footer><div class="container foot"><div><a routerLink="/" class="logo"><span>J</span> Juvino Tech</a><p class="muted">Engenharia de software explicada com clareza.</p></div><div><a routerLink="/artigos">Artigos</a><a routerLink="/sobre">Sobre</a><a routerLink="/login">Admin</a></div><p class="muted">© {{year}} João Juvino. Conteúdo para aprender e construir.</p></div></footer>`,styles:[`
.topbar{position:sticky;top:0;z-index:30;border-bottom:1px solid color-mix(in srgb,var(--line),transparent 30%);background:color-mix(in srgb,var(--bg),transparent 12%);backdrop-filter:blur(16px)}.route-progress{position:fixed;top:70px;left:0;right:0;z-index:40;height:3px;overflow:hidden;background:color-mix(in srgb,var(--brand),transparent 86%)}.route-progress::after{content:'';display:block;width:42%;height:100%;border-radius:999px;background:linear-gradient(90deg,var(--brand),var(--brand-2));box-shadow:0 0 12px color-mix(in srgb,var(--brand),transparent 30%);animation:route-loading .85s ease-in-out infinite}.nav{height:72px;display:flex;align-items:center;justify-content:space-between}.logo{font-family:Manrope;font-weight:800;display:flex;align-items:center;gap:10px}.logo span{display:grid;place-items:center;width:34px;height:34px;border-radius:11px;color:white;background:linear-gradient(135deg,var(--brand),var(--brand-2))}.nav nav{display:flex;align-items:center;gap:26px}.nav nav a{font-size:.92rem;font-weight:600;color:var(--muted)}.nav nav a:hover,.nav nav a.active{color:var(--text)}.theme,.menu-btn{border:1px solid var(--line);background:var(--surface);color:var(--text);border-radius:10px;width:40px;height:40px;cursor:pointer}.menu-btn{display:none}.skip{position:fixed;left:10px;top:-50px;background:var(--text);color:var(--bg);padding:8px;z-index:99}.skip:focus{top:10px}footer{border-top:1px solid var(--line);padding:50px 0;margin-top:70px}.foot{display:grid;grid-template-columns:1.3fr .7fr 1fr;gap:30px;align-items:start}.foot>div:nth-child(2){display:grid;gap:8px}@keyframes route-loading{0%{transform:translateX(-105%)}100%{transform:translateX(340%)}}@media(prefers-reduced-motion:reduce){.route-progress::after{width:100%;animation:none}}@media(max-width:700px){.menu-btn{display:block}.nav nav{display:none;position:absolute;top:72px;left:0;right:0;background:var(--surface);padding:24px;flex-direction:column;align-items:flex-start;border-bottom:1px solid var(--line)}.nav nav.open{display:flex}.foot{grid-template-columns:1fr}}
`]}) export class AppComponent{private readonly router=inject(Router);private navigationStartedAt=0;private hideNavigationTimer?:number;year=new Date().getFullYear();menu=signal(false);navigating=signal(false);dark=signal(localStorage.getItem('theme')==='dark'||(!localStorage.getItem('theme')&&matchMedia('(prefers-color-scheme: dark)').matches));constructor(){effect(()=>document.documentElement.dataset['theme']=this.dark()?'dark':'light');this.router.events.subscribe(event=>this.updateNavigationState(event))}toggleTheme(){this.dark.update(v=>!v);localStorage.setItem('theme',this.dark()?'dark':'light')}private updateNavigationState(event:unknown){if(event instanceof NavigationStart){if(this.hideNavigationTimer)window.clearTimeout(this.hideNavigationTimer);this.navigationStartedAt=performance.now();this.navigating.set(true);return}if(event instanceof NavigationEnd||event instanceof NavigationCancel||event instanceof NavigationError||event instanceof NavigationSkipped){const remaining=Math.max(0,280-(performance.now()-this.navigationStartedAt));this.hideNavigationTimer=window.setTimeout(()=>this.navigating.set(false),remaining)}}}
