import { Component,inject,signal } from '@angular/core';
import { FormBuilder,ReactiveFormsModule,Validators } from '@angular/forms';
import { ActivatedRoute,Router } from '@angular/router';import { forkJoin } from 'rxjs';
import { ApiService } from '../core/api.service';import { Project,Taxonomy } from '../core/models';import { MarkdownComponent } from '../shared/markdown.component';
@Component({imports:[ReactiveFormsModule,MarkdownComponent],template:`
<header class="editor-head"><div><p class="eyebrow">Editor Markdown</p><h1>{{id?'Editar artigo':'Novo artigo'}}</h1></div><div><button class="btn" (click)="save('DRAFT')" [disabled]="saving()">Salvar rascunho</button><button class="btn brand" (click)="save('PUBLISHED')" [disabled]="saving()">Publicar</button></div></header>
@if(message()){<div class="alert">{{message()}}</div>}
<label class="btn upload">↥ Enviar imagem de capa<input type="file" accept="image/png,image/jpeg,image/webp,image/gif" (change)="upload($event)" hidden></label>
<form [formGroup]="form"><section class="card details"><div class="field span2"><label for="title">Título</label><input class="input" id="title" formControlName="title"></div><div class="field"><label for="slug">Slug (opcional)</label><input class="input" id="slug" formControlName="slug"></div><div class="field"><label for="cover">URL da capa</label><input class="input" id="cover" formControlName="coverImageUrl"></div><div class="field span2"><label for="summary">Resumo</label><textarea class="input" id="summary" rows="2" formControlName="summary"></textarea></div><div class="field"><label for="category">Categoria</label><select class="input" id="category" formControlName="categoryId"><option [ngValue]="null">Selecione</option>@for(c of categories();track c.id){<option [ngValue]="c.id">{{c.name}}</option>}</select></div><div class="field"><label for="project">Projeto relacionado</label><select class="input" id="project" formControlName="projectId"><option [ngValue]="null">Nenhum</option>@for(p of projects();track p.id){<option [ngValue]="p.id">{{p.name}}</option>}</select></div><div class="field span2"><label>Tags</label><div class="pill-row">@for(t of tags();track t.id){<label class="check"><input type="checkbox" [checked]="selected(t.id)" (change)="toggleTag(t.id)"> {{t.name}}</label>}</div></div><label class="check span2"><input type="checkbox" formControlName="featured"> Artigo em destaque</label></section>
<div class="toolbar"><button type="button" (click)="insert('## ','')">H2</button><button type="button" (click)="insert('**','**')"><b>B</b></button><button type="button" (click)="insert('_','_')"><i>I</i></button><button type="button" (click)="insert('[','](https://)')">Link</button><button type="button" (click)="insert('![alt](',')')">Imagem</button><button type="button" (click)="insertCode()">Código</button><button type="button" (click)="insert('- ','')">Lista</button></div>
<section class="editor card"><div><h3>Markdown</h3><textarea formControlName="content" aria-label="Conteúdo Markdown"></textarea></div><div class="preview"><h3>Preview</h3><app-markdown [content]="form.controls.content.value"/></div></section></form>`,styles:[`.editor-head{display:flex;align-items:center;justify-content:space-between;gap:20px;margin-bottom:22px}.editor-head h1{font-size:2.5rem;margin:0}.editor-head>div:last-child{display:flex;gap:8px}.details{padding:22px;display:grid;grid-template-columns:1fr 1fr;gap:18px;margin-bottom:18px}.span2{grid-column:1/-1}.check{display:inline-flex;align-items:center;gap:6px;background:var(--surface-2);border-radius:9px;padding:7px 10px}.toolbar{display:flex;gap:5px;background:var(--surface-2);padding:8px;border:1px solid var(--line);border-bottom:0;border-radius:14px 14px 0 0}.toolbar button{border:1px solid var(--line);background:var(--surface);color:var(--text);border-radius:7px;padding:6px 10px;cursor:pointer}.editor{border-radius:0 0 14px 14px;display:grid;grid-template-columns:1fr 1fr;min-height:650px;overflow:hidden}.editor>div{min-width:0;padding:18px}.editor>div:first-child{border-right:1px solid var(--line)}.editor h3{font-size:.85rem;text-transform:uppercase;color:var(--muted)}.editor textarea{width:100%;height:570px;resize:vertical;border:0;outline:0;background:transparent;color:var(--text);font:14px/1.7 'JetBrains Mono'}.preview{overflow:auto;max-height:650px}@media(max-width:850px){.details,.editor{grid-template-columns:1fr}.span2{grid-column:auto}.editor>div:first-child{border-right:0;border-bottom:1px solid var(--line)}.editor-head{align-items:start;flex-direction:column}}`]})
export class EditorComponent{
 private api=inject(ApiService);private fb=inject(FormBuilder);private router=inject(Router);id=Number(inject(ActivatedRoute).snapshot.paramMap.get('id'))||null;categories=signal<Taxonomy[]>([]);tags=signal<Taxonomy[]>([]);projects=signal<Project[]>([]);saving=signal(false);message=signal('');
 form=this.fb.group({title:['',Validators.required],slug:[''],summary:['',Validators.required],content:['# Comece a escrever\n\nSeu conteúdo aqui.',Validators.required],coverImageUrl:[''],status:['DRAFT'],featured:[false],categoryId:[null as number|null,Validators.required],tagIds:[[] as number[]],projectId:[null as number|null]});
 constructor(){forkJoin([this.api.categories(),this.api.tags(),this.api.projects()]).subscribe(([c,t,p])=>{this.categories.set(c);this.tags.set(t);this.projects.set(p)});if(this.id)this.api.adminPost(this.id).subscribe(p=>this.form.patchValue({...p,categoryId:p.category?.id||null,tagIds:p.tags.map(t=>t.id),projectId:p.project?.id||null}))}
 selected(id:number){return this.form.controls.tagIds.value?.includes(id)}toggleTag(id:number){const current=this.form.controls.tagIds.value||[];this.form.controls.tagIds.setValue(current.includes(id)?current.filter(x=>x!==id):[...current,id])}insert(before:string,after:string){const c=this.form.controls.content;c.setValue(c.value+`\n${before}texto${after}`)}insertCode(){this.insert('`'.repeat(3)+'typescript\n','\n'+'`'.repeat(3))}
 upload(event:Event){const file=(event.target as HTMLInputElement).files?.[0];if(!file)return;this.saving.set(true);this.message.set('Enviando imagem…');this.api.upload(file).subscribe({next:r=>{this.form.controls.coverImageUrl.setValue(r.url);this.saving.set(false);this.message.set('Imagem enviada com sucesso.')},error:e=>{this.saving.set(false);this.message.set(e.error?.message||'Não foi possível enviar a imagem.')}})}
 save(status:'DRAFT'|'PUBLISHED'){this.form.controls.status.setValue(status);if(this.form.invalid){this.message.set('Preencha título, resumo, conteúdo e categoria.');return}this.saving.set(true);this.message.set('');this.api.savePost(this.form.getRawValue() as any,this.id||undefined).subscribe({next:p=>{this.saving.set(false);this.message.set(status==='PUBLISHED'?'Artigo publicado com sucesso.':'Rascunho salvo.');if(!this.id)this.router.navigate(['/admin/artigos',p.id])},error:e=>{this.saving.set(false);this.message.set(e.error?.message||'Não foi possível salvar.')}})}
}
