import { Component,inject,signal } from '@angular/core';
import { RouterLink } from '@angular/router';
import { forkJoin } from 'rxjs';
import { ApiService } from '../core/api.service';
import { PostSummary,Project } from '../core/models';
import { PostCardComponent } from '../shared/post-card.component';
import { SeoService } from '../core/seo.service';

@Component({imports:[RouterLink,PostCardComponent],template:`
<section class="hero"><div class="container hero-grid"><div><p class="eyebrow">Olá, eu sou João Juvino</p><h1>Construindo software<br><em>com intenção.</em></h1><p class="lead">Fullstack Software Engineer. Escrevo sobre decisões técnicas, arquitetura e as ferramentas que transformam ideias em produtos confiáveis.</p><div class="actions"><a class="btn brand" routerLink="/artigos">Explorar artigos →</a><a class="btn" href="https://github.com/joao-juvino" target="_blank" rel="noopener noreferrer">GitHub ↗</a><a class="btn" href="https://joao-juvino.github.io" target="_blank" rel="noopener noreferrer">Portfólio</a></div></div><div class="hero-card card"><div class="status"><span></span> Disponível para novos desafios</div><pre><code><i>const</i> engineer = &#123; focus: <b>'impacto'</b>, stack: [<b>'Java'</b>, <b>'Angular'</b>], principle: <b>'clareza'</b> &#125;;</code></pre><div class="metric"><strong>Conteúdo prático</strong><span>Sem atalhos. Sem ruído.</span></div></div></div></section>
<section class="section"><div class="container"><div class="section-head"><div><p class="eyebrow">Leitura selecionada</p><h2>Artigos em destaque</h2></div><a routerLink="/artigos">Ver todos →</a></div>@if(loading()){<div class="grid">@for(x of [1,2,3];track x){<div class="skeleton"></div>}</div>}@else if(error()){<div class="alert">O servidor está demorando para responder. <button class="btn" (click)="load()">Tentar novamente</button></div>}@else{<div class="grid">@for(post of featured();track post.id){<app-post-card [post]="post"/>}</div>}</div></section>
<section class="section tech"><div class="container"><p class="eyebrow">Tecnologias</p><h2>Do código à produção.</h2><div class="tech-grid">@for(t of technologies;track t.name){<div class="tech-item"><span>{{t.icon}}</span><div><strong>{{t.name}}</strong><small>{{t.area}}</small></div></div>}</div></div></section>
<section class="section"><div class="container"><div class="section-head"><div><p class="eyebrow">Laboratório</p><h2>Projetos em construção</h2></div></div><div class="projects">@for(p of projects();track p.id){<article class="project card"><span class="num">0{{$index+1}}</span><div><h3>{{p.name}}</h3><p class="muted">{{p.description}}</p><div class="pill-row">@for(t of p.technologies;track t){<span class="tag">{{t}}</span>}</div></div>@if(p.githubUrl){<a [href]="p.githubUrl" target="_blank" aria-label="Abrir projeto">↗</a>}</article>}</div></div></section>
<section class="container cta"><div><p class="eyebrow">Continue explorando</p><h2>Boas ideias merecem ser compartilhadas.</h2></div><a class="btn primary" routerLink="/sobre">Conheça minha trajetória →</a></section>`,styles:[`
.hero{padding:100px 0 70px;background:radial-gradient(circle at 80% 10%,color-mix(in srgb,var(--brand),transparent 82%),transparent 34%)}.hero-grid{display:grid;grid-template-columns:1.35fr .8fr;gap:70px;align-items:center}.hero h1 em{font-style:normal;color:transparent;-webkit-text-stroke:1.5px var(--text)}.lead{font-size:1.15rem;color:var(--muted);max-width:650px}.actions{display:flex;flex-wrap:wrap;gap:12px;margin-top:32px}.hero-card{padding:28px;transform:rotate(1.5deg)}.status{font-size:.8rem;color:var(--muted)}.status span{display:inline-block;width:8px;height:8px;background:var(--brand-2);border-radius:50%;box-shadow:0 0 0 5px color-mix(in srgb,var(--brand-2),transparent 80%)}pre{white-space:pre-wrap;background:#0b1020;color:#dfe5ef;border-radius:16px;padding:24px;margin:25px 0;font:500 .85rem/1.8 'JetBrains Mono'}pre i{color:#a88cff}pre b{color:#63dbc7}.metric{display:grid}.metric span{color:var(--muted);font-size:.85rem}.tech{background:var(--surface)}.tech-grid{display:grid;grid-template-columns:repeat(4,1fr);border:1px solid var(--line);border-radius:20px;overflow:hidden;margin-top:30px}.tech-item{display:flex;align-items:center;gap:14px;padding:24px;border-right:1px solid var(--line);border-bottom:1px solid var(--line)}.tech-item span{font:700 1.1rem 'JetBrains Mono';color:var(--brand)}.tech-item div{display:grid}.tech-item small{color:var(--muted)}.projects{display:grid;gap:12px}.project{padding:25px;display:grid;grid-template-columns:55px 1fr auto;gap:20px;align-items:center}.project h3{margin:0}.num{font:700 1rem 'JetBrains Mono';color:var(--brand)}.project>a{font-size:1.5rem}.cta{padding:55px;background:linear-gradient(135deg,var(--brand),#743bc9);color:#fff;border-radius:26px;display:flex;align-items:center;justify-content:space-between;gap:30px}.cta h2{margin:.3rem 0}.cta .eyebrow{color:#cafff7}@media(max-width:850px){.hero-grid{grid-template-columns:1fr}.hero-card{display:none}.tech-grid{grid-template-columns:repeat(2,1fr)}.cta{align-items:start;flex-direction:column}}@media(max-width:500px){.hero{padding-top:65px}.tech-grid{grid-template-columns:1fr}.project{grid-template-columns:35px 1fr}.project>a{display:none}.cta{padding:30px}}
`]})
export class HomeComponent{
 private api=inject(ApiService);featured=signal<PostSummary[]>([]);projects=signal<Project[]>([]);loading=signal(true);error=signal(false);
 technologies=[{name:'Java',area:'Backend',icon:'{ }'},{name:'Spring Boot',area:'APIs',icon:'◎'},{name:'Angular',area:'Frontend',icon:'△'},{name:'TypeScript',area:'Web',icon:'TS'},{name:'Docker',area:'DevOps',icon:'□'},{name:'PostgreSQL',area:'Dados',icon:'DB'},{name:'AWS',area:'Cloud',icon:'☁'},{name:'Arquitetura',area:'Design',icon:'⌘'}];
 constructor(){inject(SeoService).set('Engenharia de software com intenção','Artigos práticos sobre Java, Spring Boot, Angular, Docker e arquitetura.');this.load()}
 load(){this.loading.set(true);this.error.set(false);forkJoin({posts:this.api.posts({featured:true,size:3}),projects:this.api.projects()}).subscribe({next:r=>{this.featured.set(r.posts.content);this.projects.set(r.projects);this.loading.set(false)},error:()=>{this.error.set(true);this.loading.set(false)}})}
}
